---
images:
  - name: OSISM CI
    enable: true
    shortname: osism-ci
    format: qcow2
    login: ubuntu
    min_disk: 8
    min_ram: 512
    status: active
    visibility: public
    multi: true
    meta:
      architecture: x86_64
      hw_disk_bus: scsi
      hw_rng_model: virtio
      hw_scsi_model: virtio-scsi
      hw_watchdog_action: reset
      hypervisor_type: qemu
      os_distro: ubuntu
      os_version: '24.04'
      provided_until: none
      replace_frequency: quarterly
      uuid_validity: last-3
    tags: []
    versions:
      - version: 'YYYYMMDD'
        url:
          https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/osism-ci-image/osism-ci-image.qcow2
        checksum: sha256:CHECKSUM
        build_date: YYYY-MM-DD
