---
- secret:
    name: MINIO
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - UvhnOKb7o8HywxSWusD6ibKV/VNAShXBN2/AYtryhQLdEz/44fi6VFOp6pgy8KsQQIbyl
          56GXdNU6uRQTQhrcYpjKK9i2xMOXxc0l/5cyBXubbWkV5DkikGmYZCcjK1em6BYQTxRKT
          KjfBV59OB5sONgywgJzoZwVRKx/knFq/7Bx4S+f+ysLuiWRhvBSS1iJrdZOsgiKD5ag2e
          hajKIrtQxcXytOfb5zx2KlsS3ghVJzEVGrsjAex9NOz+/896ugOU/0aJ2zbWiFzPiL7tT
          7ZBrU1EzHqBAEfXcMFFYBfJ3tQs+ACVaIu1sG3INDHdqshvYgs9FBr+eJIRAiBNatJhhM
          b+MtrHqsiHwd7sLkTUKBdz0bpAk1QVYFCLOBVIOeub8RSRrYTwfIHF9elbDoh9GjQRBdj
          9gaEVeEBqSyB7vpYgo9zds+2Mkyx9WKLWYfCGdeCWHY+j8Vf7YwsyCIg4gDIpt9/LKGl1
          IH2/yAgyvH4JIe8FBbVx2yt9xW0E9Y5HKFHc96/FQGhgwzWQjGMa0rRGXQaZFyV/R+mm7
          aMWppCRq7q0l+OMU6+W4XyO16/BfxvjRQHiind3az4Q1ZcEY32BW6T/eEkUSPlsn0bUn+
          TI7XJnfQSokqQQHcELJshbnLipgBGAY3BaH4MYt0xvhDnwJhzNQ0162Y8yqEYI=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - jnHte4gBBrY6+CMC9Ipqb3YVMSdRjdjHQdBSCCHRRezE90BUgRzJNdPGFBhPyuIXyqnA7
          UYOYbKwxP3ht3Xa/AEZXlMGZR+oBRfWwl9B2kzKqM6YMK4mbnv1OhHD81YFRLMwDxq8lt
          Na1MW7tbGNnJ+bntbZiZN15K/xL0YjHCpn/y4ZHXrEUHdvxSWWTTKtWJrB5G98hwrHLE1
          vUp3GbVUta+YlgVlQCMTQN5AU5NCgFGhBl9f61qMCd1GEK8xATbTOiD7CjuwdSaEkiyCm
          8H13grn742fnEgl4ve8b4zzt0IL/mm0fqJTgd0cEWaSWCJX+6+ATW/Us6RIqLaXNWLPqN
          DSdHt9r0Aw55w5hcu7kKQ3OBPxXAgyhyy/aU+oCPcAilbdqHnGevzU4kqbGInc7XrflAG
          x6TWCK4+GTih3ysMDtuhpu4OCC19RLRdCdMPWDIAOLSwmk3jcwArA+h+l1hWXTxBFA6zh
          Tt+fVV0+B8JoTj5/IQcWxE9qbhPGQZSOFEMeMP/AuDYdRqz10KflNdx5QXt29tuOuTvFB
          QOxH+zaqra7j9x8k1wvo94kDn8zqXpy1KV9TH38GwkQLhXbjSBalAFyvmra0/hlWhTk3J
          vpo+EIEGACtN3Eq74dCInCzPgIT2jTSdfJO/AKAqJIMoCuxUVM7du/lVjFzXAw=

- job:
    name: ci-image-build
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: ci-image-build-zed
    parent: ci-image-build
    vars:
      version_openstack: zed
      upload_image: false

- job:
    name: ci-image-publish-zed
    parent: ci-image-build
    vars:
      version_openstack: zed
      upload_image: true
    secrets:
      - name: minio
        secret: MINIO
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ci-image-build-zed
    post:
      jobs:
        - ci-image-publish-zed:
            branches: main
