---
- secret:
    name: SECRET_CI_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - H4ogmsFc+LKgURU0lCjOULwqcgk5HFw4v36gj7tHwxDurVmjsg/JJnUMrAlWV0PhjlOzc
          n+zO7fPfivcQyFrFAFg1wxAToguRWQyTc69VC6hy6iH3oif29GmMJwSv7RaIrP2azjOeE
          hBoLpdudYbSgWH5iPI5ImCxCZG/Y5iSlAyVyi+FGDI2P5bSWmhaJ0ihm8ON9f9BMjJesd
          f44vYEhRQcxuET4MnFWIfIi1H8+4qrOXTRa+EbJh1rbppCORj5ga/uOhYQXJzD/hAR4YM
          eV8SDc1jHkrKciHl5hB0gybxGrGOWICBKTm7esFDNLTV1rSfneUAAk68WLYQ/QaJ2HAmD
          2yo+DDRrmMvUCIPMhGRtgvzJ9m7sw6NEyqkFZXWIcnmJXMtzw59JyZBkzk9vyTzO2G8p6
          2V2mP0FCjMq2pibgyNHVS+Thq8i2ha+lYdpakK1O/rbU6EbLx0IAyxa/oNxUCVb27wKkB
          AtgPOw2ZwPHruiciYAdAK3dsUaeHEkALgokeC4ZaeQKMZ/B7vu11kOnVB0UMXcD79usWZ
          K+S2bDnA2PD8PqJ9L7jh9YHVJboCTWbXypSUaSgH4YLsObjT+Ph4+4WE3upIFNx5PC3CA
          ThBanBLWdQRVeKYKGAd4FBC/buu31hqZC0/HtZXJ+iyGyY7YE7FUvZV2BUDJOA=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - Mc27N0FQcejh9Z3PnablNK0MyVMaCotoFV/gXJ+z6FjD35SSS/5SvnT1Kjlk/fPIYPiQG
          DgySP047oNgcrMerPGRWoHNYowukxowYAiYbflW+kdJsunYBE4qAgzpz2dGBbTAJX42q/
          8Bf+dyi+yVTOx4Yx2Wwbq+r9v6ci8viycvsSme/Ecw5z3raOc4ohDfNxxk1DPZhkuK4nT
          AkXUYPUBrIZgiNZ6DbzyM3/HMom2+7VdLbCJqyouChXzH8oTvdVLZNEAUTohfKEBWgp2Y
          giulLVLsVX3OiFPb2EL7y7Slg9UNqDVNtzZ4+w0EHujdeSqjYfYa6NuOrujiFyvthCb3Z
          Y0mUjm9vd9OtjO5UANbrEy2d9QEtakX366Vem7R3QC+KGAU3O5NdhSrcUYhK4YUGsx7EV
          y/h898KVcK495EiNDtK94ltR0FnO6P+oXymTmxkrP/Q6Fx0lCty7LqKLAnJbEX1Ic85ae
          oUgaBZepxUEeAh0wgsr9KJo9+0/zweIDH7iBSwZRiUuWfa62PXbts8q4HGFQStwEle8sq
          4mlPMzllxHXf5Cr2xpZKwA7cXcoUOEuliMo8AhmAxVr1kHK7zuBFgnua+ZWS9qY/I4A9K
          VllPsloDt1uvh2lXx9YHIIW4lkth5FCV/TQFx7FrV0z11MwHE9CKrEINxO5p8Q=

- semaphore:
    name: semaphore-ci-image-publish
    max: 1

- job:
    name: ci-image-build
    nodeset: ubuntu-noble-large
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false
    irrelevant-files:
      - ^.images.yml$
      - ^LICENSE$
      - ^README.md$

- job:
    name: ci-image-publish
    parent: ci-image-build
    semaphores:
      - name: semaphore-ci-image-publish
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_CI_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - ci-image-build
        - yamllint
    post:
      jobs:
        - ci-image-publish:
            branches: main
