---
- secret:
    name: SECRET_CI_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - K13hyZjCJZSb7js2oN9VfoDJj5XBgJJC5Ms4S6Bkt1vq0+EfSLHD4vjnC0VcNw3izanF5
          FoS0xqyFBSB7xXuVQnXjkYoiMVD7XXnfqiktCBxHopG3TsrMM/+ryDrdhXfoSM8gjE4dS
          eqR62eRJMACR0tghDKaOUFZRxYIcmlu5IVscMmy4HqvMg+wsNLLPma/TuGJbBOu0+tYnX
          chx6krJC8ijteQY+oSTu7aXhTZb+64cwFK26nhI+kcxbKojWny1v0fV9M9PGZaFHaRnyZ
          5Cg6cLlUZR6cGGex/a/w1s92qZgynvRcaWhoI/WrVU2RtXRpqOaOj+0SB71MeOd55TT8R
          bbCyUe1NC9pVgog10tDwfDSs3vGJ/P+ch6PWGE2OFpPuw2v0OmK60arAxVrfXP3tKtob4
          dHhNcYc0Z6IgkendH5n0s9muf98011Vm7tAKPynIYzIWeuqN5tw1nM4X61UxDxrGbyDiw
          XGQdOV2WN/RU+e7i2WS1KAHwXPLsj0BZzIjh+vBOnOLwXS8R7Q4QkNPAyMkms16xqap6q
          iBtkb6+0XfegOF9w7u8AegYuCCcKlHxOCXYjtfhrbVbmYgGKogQRMNt4KQOfgpiHPWDHL
          aymb+ENgsBmcFQdg9gOQwXHRuyUxuZZRQj/mTokdbOnt6cyRwuccvqYMZdODS4=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - ll6S+2yUXMx0iiEOHw3hcP2OprU5dM7h1ABo3X3NX/XNhwzD/VSo1YWGQNxPxHvNZrdAg
          WEuOqh7wTaavGIamPvbWJJi6o4dHxRG6PU7e4OxPDJoARYUdB51hb/jgChhsgivVC4x0S
          oYXXXZsziHpVuY3p4fJVMZ/oighfLT0KSeEHaaWbcsdBSYmDGVFDBuSD7e1TbF8qJDlj5
          QYhNP1ACUsfFWPNCV5ONflQmki6JBnJdTfRJ6cV1xDWiXPwNroGcS8ahRK7Gl2/E4+lcP
          9uuADXP5hNFGlc7k4MzvhT+lU4OOzalgcwJUTsDHKEG7R92lRPxeAbPktMdP0PJ6oNT6r
          tr0jo+G+KQ/EHd1IWhoLGSINgnT6MLERd8kW5r4QIev7VCSIreGrTuE5W42ANSmwj/rjv
          eiNdJsM6oEc7S8x23etygBCxzbtJ+TNTH16Hq5eqdERzL2X1R7tRWmaAH8NO5fCIBEFwR
          OrSMt3yXl6hW8K8nmIKuadOdHH5BEvyqITDmNVloqXZRr6aPfjtfyxJKi9ZVLGYdqrnEI
          O+I6Ffd5ul54/+dSDhig7or2rVfb+fsBB6uT0xQNMUathYmc0KhcGcVp8fhHYFXbIyBo5
          w0/V/JCzwIp2FUY1qcKm7he9C9zcrpHnWlikW13x+AXvXmZ+89XH93QO0+vC3I=

- job:
    name: ci-image-build
    nodeset: ubuntu-jammy-large
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false
    irrelevant-files:
      - ^LICENSE$
      - ^README.md$

- job:
    name: ci-image-publish
    parent: ci-image-build
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_CI_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ci-image-build
    post:
      jobs:
        - ci-image-publish:
            branches: main
