---
- secret:
    name: SECRET_CI_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - q2M+CBhy6ttUjEUYdwjfV3loqnkReH3PnI+j5HCgurW+VjmIwQFYnVbC2E7CyC2HR5jc4
          lGqHO6ZV2vdX0i2hBbnhi/hV+vOOqXgNV7C0IEwOfdy4QcWJfuHZ159xvi/hyZHE2jpsl
          wBO0/0POmoFIxv6MM3YXA1NzZPt2n4EjIMSWyq7nigjNLAKiUn/mw/06tcJmKA3bvg3yK
          fw1IRvQPlL+aaEFeFEW19ty/Eh5FqORdeCy6PcmP+8sx2hvdWoJNKg59DKL5axz57PUF5
          Qq9/v105s3LpI8B1E5FD7iEJ6MSykvSLAIKbV9CVhYhGijF5Pu80Rd9ytA0pDIdZKxiTg
          l2GsacIDIbhqtw5tfqxXLTR+OgMvjgs6K5rlN0iDWPOKOxg1+OAI4dObxnTxMH9kXUxKH
          iyquKephBUe3JwDP2LR3YidcU1AkEKD08DL79PYbvdrc2pbKmJB8+aGCIWCNFVAQo7pbO
          Bp/6MrnSs9hXS5XUYqxFgNV1/NbzWq85+O2NonohC6hIgspOxThWVrjPKenvk0XasZiN7
          a6fo/UiUhF/UL4vvL+GCbXY0Vnxxj7Xcm1QuV1p5lIFH/OQmyiSKL9QVac6UokjswnI04
          +jL+uC0frMASDc44KRnD+gAVlFQLXUEfSbgb/xvDYRfaXqc9urGsH9r0n1yupU=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - wTXcfgn+s2u7YASnbI1OMXAFbLHJUMMv2Ny4pFtSvEUDsVA1lxqxltds2quSN4rwuG92p
          kdaGLFtCn49+y2azAL1/uhBskRtDj0Y10UKrJkmS4S8SweRWzxICSXjD/52gAjEYnldlJ
          ya6FfJGMPktDaHNsmFwSajLiA1/nl2Y6VNmkswst0BXE+NT/X3gPg9gghYu++PB/Vw3MH
          Ecfibz34nRTaJzC5E6xKmBqsmEZy3NdJzx8NsUHDx01laB3FVTCYBrW+9Vsv/qAXqEoPP
          Hun4Xi4uHwMa89RpFHBt61n/JKvNs3WvPGaRP+4dDgjwB7qLKod0syOmx8OgtVTvfRmQy
          13tv70vlORX+7qa73Odjb20S1O6tDJpjIrkKVrBNivFAoHGy1rTxIckclq2F4/crPHYbe
          EJarGsVqTOvJZs/xKgkijNHxMNwBG7cmVf5TDagbYPcoituadLiHWgDlvYJmS6BbEKuph
          XQ1gnOXXGYUk3JoyGF8qJ4p7iIQ3x2A0ri6DXDbDJKw1FigIuuWnIrhpeIbeSy6CEvLOj
          OzDpnhwe56OWEEUqgL76N9tv9VQerfAsqBwsd24klVAm8ZQr2ye3new4lqGvnGQcmh06I
          FuMNAxI+0Kklzsl0+/utKIO/Vlo2DHKNk34F62fqNk7NBojHbZXcfpCbZS8L44=

- semaphore:
    name: semaphore-ci-image-publish
    max: 1

- job:
    name: ci-image-build
    nodeset: ubuntu-noble-large
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false
    irrelevant-files:
      - ^.images.yml$
      - ^LICENSE$
      - ^README.md$

- job:
    name: ci-image-publish
    parent: ci-image-build
    semaphores:
      - name: semaphore-ci-image-publish
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_CI_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - ci-image-build
        - yamllint
    post:
      jobs:
        - ci-image-publish:
            branches: main
