---
- job:
    name: ci-image-build
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: ci-image-build-zed
    parent: ci-image-build
    vars:
      version_openstack: zed

- project:
    check:
      jobs:
        - ci-image-build-zed
        - tox-linters
    post:
      jobs:
        - ci-image-build-zed
        - tox-linters
