---
- secret:
    name: MINIO
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - ape5q8qkqcnwJJQOGNmrTj+4h6apnfmQLwNYMzP9sgIJpPIf+pp2EGVSrrSYw3IENeA9c
          qo5ktwRchbJfqRQwGlrQ2CvdfBxqHdyn61pCNa5iCSbyT25ROQaMmF/1dxblee/WasuOD
          fqi+DnmQpLbLdI8ZXBZILxBdHWRuaDIhWYEvjrNtQnww5rjxdzUhuBjJdGTJW0XGbxw+F
          M8LsuIM0VOpEdDR93pobaIAAmSFCQd4h8sA09ouiumlPrf3rG9Me9fczhltF/VAvep97a
          qJ0qECD5X1M4jXrp3ReqbVDx1BF+++oTau98lt0cPn0tcjnxIHGOfI/uIMjpSm3xAWJm4
          nmzn5MCMZaWB16Ig0UEOyJ/TRkyVZsYoQj4/lGCRRq97TCI1srwTdHoHZAzqYCmqE7EP6
          KzwWIQPLpji7Tm3rP6mUaCt+hUAnI0bwAvzx3bH6R+UXW6TpAodUx6c5EuBX2C4PCOlUG
          gMRwYezfSBmlhrJ/Qf0SUyrrYlo97RquaknZKFifDjI2d26QWA/vvdGYAuJiSWXBZHQ0o
          eOD7Gvg/o4oh3CcklZUVeUkLyVtG75tgFkpmxcDKFQHUiqK0kCedX15390MkW2ZUpVpB+
          X1xZhoP6FnUJXrVukYBr4to5lsOmmtktshq2m3ViJsn+G7F3uteCtZWPXiRYCw=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - CrbHMvuBs8y/wMrInmQ1N3G8D6I0oNqC592XmQffZIhIhjaBXZNsWjPzeN69suWmy/ohA
          KnurIJVXmNrnUBJG6rJY/uhmURrmY85rSDJ1QXURZXs2d5+UUMclB+6kBiPgYBtLltelb
          NsumQfCB8g5EjJU/J72Q6oTQN2BIiDqt6jWEqddDpc0IFS47cOyLRAw3+g5ip/VwK6Kuu
          wCoO/shto4CqdAaX1+2ZmE5MtPqkZwShX2jXgijmmG8IsPUjTs6BOJJyAEe4nT7QggWPv
          dMJ+tyOz2truQduJ29Gzs/eXnuly4ObjB1m8z8UiguhJ63AT4kNjLvNqlU9XHOE0+h1n8
          HqIx9oG9KNUlzDcNWifstf0IgHIE+n+sRaUH/TXtcDJ/mOTeANrbArPJ0RSpXVYrfZ+mQ
          UXxsuZpDfVGX/q1/2AvfPmpT43FrdEO4x0K65dlbMVgTTEx/xNEokB5ol1C3fjvXLhl5i
          7pXcKVEqSP1UwBFqWC9lAJ3qI0TYx/noYk+63FsDVd9IDdbTQo3ihj+Naf0l59VdWr2Xb
          8Iulkdklc9GCtCZpQ0+0nyAo7Wti2jZ9vsxGycLQNPLeLTVTxj2MpZZw1Cpgh7nIaCd41
          +6Hfu+r9Al/zMycXGzpqUAvUNUIMF6U2yi0MIkO2tz520jSYEr++wbC/kfS35o=

- job:
    name: ci-image-build
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: ci-image-build-zed
    parent: ci-image-build
    vars:
      version_openstack: zed
      upload_image: false

- job:
    name: ci-image-publish-zed
    parent: ci-image-build
    vars:
      version_openstack: zed
      upload_image: true
    secrets:
      - name: minio
        secret: MINIO
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ci-image-build-zed
    post:
      jobs:
        - ci-image-publish-zed:
            branches: main
