---
- secret:
    name: MINIO
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - Z9H157kb6MpXT984qSCZyJQ0qNp5XSwGF3YDDaojnZGQ/GT6D6a2BouL1mF6OM840ydR7
          0IvQrWDPLoLVd3EEYKx/CSLij1YcbtPJMRHdn/aB/ta/63sIPhyy0rVp2+nLP7FI36k9R
          u7EZRZIPNntfp79GXHWHl6cy8I7/UpvXJbt9Luzyalg3gEwmdPfhD4sMrWWcm02STYDo9
          un63SszjZPzs1wKwe92r6axsMo0CHZE3+xMJImTqSPFOlmYFqIXoPPljyIQ5mJMF7CQd3
          FXSaM5WxbLOczj0QpKkQzB2uD8y+dZz78rsG+vmIgIYpmvMzLkLgoA50/Kg0lZgWfNI2P
          ISHgVXlcjyUhiPbiJNYjZxPwUORwHuLjdrlRTWHNedf8dEWX991kpjsG8Ochn7QVtOiMH
          Gzc0JyurDY6x7G0j7cD93tCPxB/pmd2IP1SYG7ah8BfkFrN7HJEo+iQVKY1u0wZrXbvLp
          4o4zfGBXpP6ABQyNiGleOPu7XMDAVD6CRlCnw4btKRPeUKS7iKjJkPIVz5PqRKMiaKZ9W
          syoXpEL0AGElXBWAYGQNpD5ZBdtV7J6zunl//PeyoOe50Xo8BY2woqn6UjL3AGU+H1W2w
          i5SkzIikgnMv6HsDN0DbSsZ5ZVsiFEuuPtoZ8aQA8JUD6Xeh6SCmrdGb2H/gC8=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - H03fSUhWWg5XkFXakYcSAiHfc6y4QCmVFD8vNb1pocNl43J+uZKkSa64GCcL8YFQIG5/p
          0mPpjRiZWEy9YSNSdYc/MVfCXf5Emozk2etZpbouFzK09wVlzI6oxMUm/SzeeOSbxRq6v
          F00bfdxfSrra9zeD5D+Yx1gfYp23QKFzn8hHOt1cXApMiyCl2JVKXyTt8zrfCwFj/TQem
          EJlTx/U9sz32XVDmYHA09II59Mq64EX+MKSE1ToK+BgUFl7iVMQCCtSL9IDENxZKz5ktH
          pWjYIBWa/l3pun3PozHUiwaeXtq0dF1Hgi1AWKKtj1BMPimWkjs8fNnv2ANvWfORx1mZa
          Yjmd0ZFTayk4f7CkRSX+pHeyrDZaBBhy/DCeKBTKdGw+AXY7ciVXnvRx3ZymZf68p0wyo
          r8pKDNZBHRhJkSGkTV+C7bO9Pql5nP19GZPrhF+I9/CiQDCOwxnC6yG4pGVNZ3xM2x2FU
          2HcYf0YBtXB9wCKx4UXM0kH6r3LnmlxqlEf4V7IvXQ7rc9oov6qkd3Aae9ahZhAgxumy0
          8tvqsfAwbncTXUQyg3ABoCjnculfI5IDfXxT0Q+AgZ25mYljuicfueVTO5/Z8nej6+dNl
          s81+p97LdjnhIs52pCaX9YVL5PFeYspMXZcW8rDIbrYQTztaDS4Rn1toefsiv0=

- job:
    name: ci-image-build
    parent: base
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800

- job:
    name: ci-image-build-zed
    parent: ci-image-build
    vars:
      version_openstack: zed
      upload_image: false

- job:
    name: ci-image-publish-zed
    parent: ci-image-build
    vars:
      version_openstack: zed
      upload_image: true
    secrets:
      - name: minio
        secret: MINIO
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ci-image-build-zed
    post:
      jobs:
        - ci-image-publish-zed:
            branches: main
