---
- secret:
    name: SECRET_CI_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - ebbuljrxX7oApPDKYE2oSn6VSC9JBxFYqt4Sr+ppRGz67Bj2sa57hdoN90ls9sdmL9xj7
          G4bSpKyO6DM7AOQBkQOSSfpe9jXU0y3hKtW5EY02ZFiCXa/btMxDLWwb3XJklNF2Cdxn7
          XJdzTBpQAC+XDJGYtB4mGAlEX+Z+xB5THgNH4E+SIMwSC++9eRIu0Iq4kKvib/iF8NaSH
          Ya6ohpdbQnbiDU+KJ6X0lOyTXcHOSSO4g1DVMS2ayIpxwHwOGraePpjaNqzXStUyxZWsC
          dUzSwkMoSJFhqWe0o8c5Fy+FfXkisKEfF55ouESk+BKv26OO56EegaSWlkab9InLruD4V
          BuPZZ/rJ/tzJVpauAfSaaXOu+h2b9ULlFjBXFbPvSpk1vg8ASITN5whEHiorYE6lh6Qp+
          5O9JbXnYehzPPngvkkBdSWgMuNNcQJuNyGEHW7HznghyGVHizDEjgnY6YxHmEb225xz1h
          +zJ9kYqSD5ibZEHix4kOqNGbbONLwZU0wV9aoGOmo7ToSt3L4LpDofwDYIgiEDqZ0O3S2
          R1CWLTFTGacq07eHFIOrUxgq3YrVr+KZv1tKTmwWzqp5KmtND/yUYjwl9kqC8Z2fZWdKr
          yg9j9ZpcC2cp9mJJw6JssUdu0j6EbKkO7JfrSDpO6nZ7hyPK7GhsOw2/ZW5grk=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - t2dRqzpa/uMMzRnofWeNH1X4cmJJVuXCuYAzZAHix3eY3U6ELn7+z0A/FN0TsaIFhV+qX
          b1RLwgRq/C2I0r+uAFGi2SDp9he44QcDrkpq6/NClTl1eEvkfemPEGMZeI+/d3v4/BASl
          yGj4H3jhvJ112vxYRuPKBnAwOoujSTH1n487GIl8oUI7zEaxqpqFhzlC82NPOZuz+w0Em
          BjylLTCBVh8a8lGTZa8RML8uZtInfAzAVh2UjtTjNKZCKEemXKkp0UYwgnfDNHcn/eZBa
          kYcWg94KGAwVowGfU9LTe/p5YT8FvnjptuQIAQsFF1a57/v9+boIOXGZdmrfEe03KLGXB
          oX4AAJeSNgXz1R9t8kWMnNrEadblc6s81GnwIxqMebL6FwOkxFiUuD83tabO5NsOOk/Y8
          4dfwvq4o9+hiPuJS/fkdhHMlFUdHYuGRR/xncXQeLFxixrdkGXZH6mjy8INJSeZUq5y+r
          Q69aIRfugJZKuda/DJU5RdgVCEjRVjJXQdwlksZsGxqyftop8ldRv3ko3RQS8GvLX2IoC
          rBmh1K4hnW7geYpJl4yx8g/yqt8B26OO0/2NXtT8RWHR9XK1pmZchDVa7sMOA/IDKvhCU
          B0FP2x0UAXEZkoCTaoTqefc9EWi8UNmwlLLDXI9hm0R/4GqQgJcA2QXyglSVpE=

- job:
    name: ci-image-build
    nodeset: ubuntu-jammy-large
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false
    irrelevant-files:
      - ^.images.yml$
      - ^LICENSE$
      - ^README.md$

- job:
    name: ci-image-publish
    parent: ci-image-build
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_CI_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ci-image-build
    post:
      jobs:
        - ci-image-publish:
            branches: main
