---
- name: Run bootstrap
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    operator_user: dragon
    operator_group: dragon

    cleanup_cloudinit: false
    cleanup_packages_extra:
      - snapd

    required_packages_extra:
      - linux-generic-hwe-24.04
      - python3-netaddr

  roles:
    - osism.commons.operator
    - osism.commons.systohc
    - osism.commons.configfs
    - osism.commons.packages
    - osism.commons.sysctl
    - osism.commons.limits
    - osism.commons.services
    - osism.commons.motd
    - osism.services.rng
    - osism.commons.cleanup
    - osism.services.chrony
    - osism.services.journald
    - osism.services.lldpd

- name: Apply role docker
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_configure_repository: true
    docker_configure_storage_driver: true
    docker_storage_driver: overlay2
    docker_user: dragon
    docker_opts:
      max-concurrent-downloads: 20
    docker_insecure_registries:
      # Pass through cache for Docker Hub
      - nexus.testbed.osism.xyz:8191
      # Pass through cache for Quay
      - nexus.testbed.osism.xyz:8192
      # Pass through cache for OSISM Harbor
      - nexus.testbed.osism.xyz:8193
    # renovate: datasource=github-releases depName=moby/moby
    docker_version: '5:28.4.0'
    docker_facts: false

  roles:
    - osism.services.docker

- name: Apply role docker_compose
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    docker_compose_install_type: package

  roles:
    - role: osism.commons.docker_compose

- name: Other preparations
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Create /etc/osism-ci-image file
      ansible.builtin.copy:
        content: 1
        dest: /etc/osism-ci-image
        owner: root
        group: root
        mode: 0644
