---
 - name: Build ci-image
   hosts: all

   vars:
     version_openstack: zed

   tasks:
     - name: Run install script
       ansible.builtin.shell:
         executable: /bin/bash
         chdir: "{{ zuul.project.src_dir }}"
         cmd: |
           set -e
           set -x
           scripts/001-install.sh

     - name: Run build script
       ansible.builtin.shell:
         executable: /bin/bash
         chdir: "{{ zuul.project.src_dir }}"
         cmd: |
           set -e
           set -x
           export OPENSTACK_VERSION={{ version_openstack }}
           export PATH=/home/zuul/.local/bin:$PATH
           scripts/002-build.sh
