---
- name: Build image
  hosts: all

  vars:
    python_venv_dir: /tmp/venv

  tasks:
    - name: Run build script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -x

          source {{ python_venv_dir }}/bin/activate

          export ELEMENTS_PATH=./elements
          export DIB_CLOUD_INIT_DATASOURCES="ConfigDrive, OpenStack"
          export DIB_RELEASE=noble

          disk-image-create \
            -a amd64 \
            -o osism-ci-image \
            --image-size 8 \
            vm ubuntu ci-image

          qemu-img info osism-ci-image.qcow2
          sha256sum osism-ci-image.qcow2 > osism-ci-image.qcow2.CHECKSUM
      changed_when: true

    - name: Run upload script
      ansible.builtin.shell:  # noqa command-instead-of-module
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          sed -i '' "s/YYYYMMDD/$(date +%Y%m%d)/g; s/YYYY-MM-DD/$(date +%Y-%m-%d)/g" .images.yml
          sed -i '' "s/CHECKSUM/$(awk '{print $1}' osism-ci-image.qcow2.CHECKSUM)/g" .images.yml
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio https://swift.services.a.regiocloud.tech {{ minio.MINIO_ACCESS_KEY | trim }} {{ minio.MINIO_SECRET_KEY | trim }}
          ./mc cp osism-ci-image.qcow2 minio/osism-ci-image
          ./mc cp osism-ci-image.qcow2.CHECKSUM minio/osism-ci-image
          ./mc cp .images.yml minio/osism-ci-image/images.yml
      when: upload_image | bool
      no_log: true
      changed_when: true
