---
- name: Build image
  hosts: all

  tasks:
    - name: Run build script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -x
          export OPENSTACK_VERSION={{ version_openstack }}
          export PATH=/home/zuul/.local/bin:$PATH
          export ELEMENTS_PATH=./elements
          export DIB_CLOUD_INIT_DATASOURCES="ConfigDrive, OpenStack"
          export DIB_RELEASE=jammy

          disk-image-create \
            -a amd64 \
            -o ci-image \
            --image-size 8 \
            vm ubuntu ci-image

          qemu-img info ci-image.qcow2

    - name: Run upload script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio https://minio.services.osism.tech {{ minio.MINIO_ACCESS_KEY | trim }} {{ minio.MINIO_SECRET_KEY | trim }}
          ./mc cp ci-image.qcow2 minio/ci-image
          ./mc policy set download minio/ci-image/ci-image.qcow2
      when: upload_image|bool
      no_log: true
