---
- name: Run bootstrap
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    operator_user: dragon
    operator_group: dragon

    cleanup_cloudinit: false

  roles:
    - osism.commons.operator
    - osism.commons.packages
    - osism.commons.motd
    - osism.services.rng
    - osism.commons.cleanup
    - osism.services.chrony
    - osism.services.lldpd
    - osism.services.journald

- name: Apply role docker
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_configure_repository: true
    docker_configure_storage_driver: true
    docker_storage_driver: overlay2
    docker_user: dragon
    docker_version: "5:20.10.24"
    docker_facts: false

  roles:
    - osism.services.docker

- name: Apply role docker_compose
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    docker_compose_install_type: package

  roles:
    - role: osism.commons.docker_compose

- name: Pull images
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    images:
      - "index.docker.io/hashicorp/vault:1.12.3"
      - "index.docker.io/library/adminer:4.8.1"
      - "index.docker.io/library/mariadb:10.10.3"
      - "index.docker.io/library/postgres:15.2-alpine"
      - "index.docker.io/library/redis:7.0.8-alpine"
      - "index.docker.io/library/traefik:v2.9.6"
      - "index.docker.io/phpmyadmin/phpmyadmin:5.2.1"
      - "quay.io/osism/netbox:v3.4.4"

  tasks:
    - name: Install skopeo
      become: true
      ansible.builtin.apt:
        name: skopeo
        state: present

    - name: Create /opt/images directory
      become: true
      ansible.builtin.file:
        path: /opt/images
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Pull image
      become: true
      ansible.builtin.command:
        cmd: "skopeo sync --src docker --dest dir {{ item }} /opt/images"
      loop: "{{ images }}"
